apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tp1-backend.fullname" . }}
  labels:
    app: {{ include "tp1-backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tp1-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tp1-backend.name" . }}
    spec:
      containers:
        - name: {{ include "tp1-backend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
