apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tp1-frontend.fullname" . }}
  labels:
    app: {{ include "tp1-frontend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tp1-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tp1-frontend.name" . }}
    spec:
      containers:
        - name: {{ include "tp1-frontend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: VITE_API_BASE_URL
              value: "{{ .Values.env.VITE_API_BASE_URL }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
